### PR TITLE
Conversion to KDSL gradle scripts

### PR DESCRIPTION
**Pull request by mpetuska**

### CODE REVIEW

**Comment by rjaros** [comment]
I have a problem with new configuration. Building for development and production somehow interact and conflicts with each other. I can run `webpack-run` task and it works ok as long as I don't run `-Pprod=true zip`. After this, the webpack builder is failing, HMR is not working anymore and the browser console displays warnings about missing source maps. When I clean the project and run `webpack-run`, everything is again correct.

**Comment by mpetuska** [comment]
Hmm. I'll look into it

**Comment by rjaros** [comment]
And another, very strange problem. The `addressbook-fullstack-jooby` example. When I first run `frontendRun` it build and runs the application correctly. But when I change something in the sources (even a simple string value) and run `frontendRun` again, it fails with:

```
> Task :compileKotlinFrontend FAILED
e: java.lang.IllegalStateException: Arrays of class literals are not supported yet
        at org.jetbrains.kotlin.serialization.deserialization.AnnotationDeserializer.resolveArrayElementType(AnnotationDeserializer.kt:144)
        at org.jetbrains.kotlin.serialization.deserialization.AnnotationDeserializer.resolveValue(AnnotationDeserializer.kt:97)
        at org.jetbrains.kotlin.serialization.deserialization.AnnotationDeserializer.resolveArgument(AnnotationDeserializer.kt:64)
        at org.jetbrains.kotlin.serialization.deserialization.AnnotationDeserializer.deserializeAnnotation(AnnotationDeserializer.kt:51)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptPackageFragment$FileHolder$annotations$2.invoke(KotlinJavascriptPackageFragment.kt:70)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptPackageFragment$FileHolder$annotations$2.invoke(KotlinJavascriptPackageFragment.kt:68)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:346)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:402)
        at org.jetbrains.kotlin.storage.StorageKt.getValue(storage.kt:42)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptPackageFragment$FileHolder.getAnnotations(KotlinJavascriptPackageFragment.kt)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptSerializationUtil.serializeFiles(KotlinJavascriptSerializationUtil.kt:239)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptSerializationUtil.serializeDescriptors(KotlinJavascriptSerializationUtil.kt:216)
        at org.jetbrains.kotlin.serialization.js.KotlinJavascriptSerializationUtilKt.missingMetadata(KotlinJavascriptSerializationUtil.kt:330)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.updateMetadataMap(K2JSTranslator.kt:176)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translate(K2JSTranslator.kt:144)
        at org.jetbrains.kotlin.js.facade.K2JSTranslator.translateUnits(K2JSTranslator.kt:104)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.translate(K2JSCompiler.java:169)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:311)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:85)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:158)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:64)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:237)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:88)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.execJsIncrementalCompiler(CompileServiceImpl.kt:522)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execJsIncrementalCompiler(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$3.invoke(CompileServiceImpl.kt:467)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$3.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1005)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:138)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1047)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1004)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:466)
        at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlinFrontend'.
> Internal compiler error. See log for more details

```
I'm not able to compile the sources anymore. I have to clean the project. And then the build is OK - till next source code change. It looks like some problem with serialization plugin and multiplatform build.

**Comment by rjaros** [comment]
The same problem is also in `addressbook-fullstack-ktor` project.

**Comment by mpetuska** [comment]
I've updated the PR. Now if you do:

1. `./gradlew webpack-run` -> HMR works
2. `./gradlew frontendZip -Pprod=true` -> HMR breaks
3. `./gradlew frontendZip` (or anything that forces the compile without -Pprod=true) -> HMR works again

Hope that's acceptable.

**Comment by mpetuska** [comment]
As for the other thing, it's unfortunately a compiler bug: https://youtrack.jetbrains.com/issue/KT-28927

There's a workaround described here: https://discuss.kotlinlang.org/t/kotlin-js-compiler-crash-arrays-of-class-literals-not-supported/12646

**Comment by rjaros** [comment]
Now I remember, I've encountered this problem before. And it wasn't really MPP problem but an incremental compilation problem. I've managed to workaround the problem with `kotlin.incremental.js=false` option in `gradle.properties`. And you have removed this option in your PR.

**Comment by mpetuska** [comment]
Yep that fixes it. I was wondering why you had that disabled :D 
Gonna put it back.

**Comment by mpetuska** [comment]
Also, could you invite me to this and main repo? I'd love to help this framework grow.

**Comment by rjaros** [comment]
I think we can merge this now. There are probably some other issues, but without intensive testing we will not find them. In my opinion it's a superb work. The build files look a lot better then before. Thx again.
After all the projects are converted I'll update the guide with new instructions.

**Pull request merged**
