### PR TITLE
Gradle Kotlin DSL Examples with new MPP model

### PR DESCRIPTION
**Pull request by mpetuska**

### CODE REVIEW

**Comment by rjaros** [comment]
Nice work! Thank you.
Have you tried applying DCE plugin with new MPP?

**Comment by mpetuska** [comment]
DCE is no longer needed since kotlin-frontend plugin handles this by default with `webpackBundle.mode="production` since `0.0.45`

**Comment by rjaros** [comment]
I'm not sure it is working. When I build your mpp-pokedex with production mode I get bundle of 1,9MB. In the old project it was 0,9MB.

**Comment by mpetuska** [comment]
I'm currently rewriting all examples with KDSL. I'll look into DCE as well

**Comment by rjaros** [comment]
Great! But it's a hell of a work! 
Don't you want to wait with this until all the recent changes to the Kotlin/JS tooling will be officially published and documented? I'm not sure, but when kotlin-frontend-plugin will be deprecated, all your hard work could go to waste and we would not want that to happen!

**Comment by mpetuska** [comment]
I've been trying it out for this already, however the lack of docmmentation for it makes it troublesome. Also converting groovy to kotlin dsl isn't all that hard once you know the basics. I'll of corse update them once kotlin-frontend is deprecated.

**Comment by rjaros** [comment]
Nice! :)

**Pull request merged**
